name: Deploy Gatsby

on:
  push:
    branches:
      - gatsby-london

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.JEKYLL_PAT }}
          deploy-branch: gatsby-london-publish
